server:
  port: ${port:8881}


xxl:
  job:
    admin:
      addresses: http://192.168.80.1:8888/xxl-job-admin
    executor:
      appname: xxl-job-executor-sample
      port: ${executor.port:9999}
    accessToken: default_token
