version: '3.8'
services:
  headlines-mysql:
    hostname: headlines-mysql
    container_name: headlines-mysql
    privileged: true
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --max_connections=2000 --max_allowed_packet=64M
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123123
    volumes:
      - D:\mycode\IdeaProjects\04microservices\heima-leadnews\env\mysql-volume\data:/var/lib/mysql
      - D:\mycode\IdeaProjects\04microservices\heima-leadnews\env\mysql-volume\conf:/etc/mysql/conf.d
    ports:
      - "3307:3306"
    image: mysql:5.7

  headlines-redis:
    hostname: headlines-redis
    container_name: headlines-redis
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    image: redis:7.0.4-bullseye

  headlines-nacos:
    hostname: headlines-nacos
    container_name: headlines-nacos
    environment:
      - TZ=Asia/Shanghai
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=192.168.80.1
      - MYSQL_SERVICE_PORT=3307
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123123
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=10000&socketTimeout=3000&autoReconnect=true&useSSL=false&serverTimezone=UTC
      - JVM_XMS=128m
      - JVM_XMX=128m
      - JVM_XMN=128m
    ports:
      - "8848:8848" 
    image: nacos/nacos-server:v2.1.1

  headlines-nginx:
    hostname: headlines-nginx
    container_name: headlines-nginx
    volumes:
      - D:\mycode\IdeaProjects\04microservices\heima-leadnews\env\nginx-volume\conf\nginx.conf:/etc/nginx/nginx.conf
      - D:\mycode\IdeaProjects\04microservices\heima-leadnews\env\nginx-volume\html:/usr/share/nginx/html:ro
    ports:
      - "6001:6001"
      - "6002:6002"
    image: nginx:stable-perl

  headlines-minio:
    hostname: headlines-minio
    container_name: headlines-minio
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - D:\mycode\IdeaProjects\04microservices\heima-leadnews\env\minio-volume\config:/root/.minio
      - D:\mycode\IdeaProjects\04microservices\heima-leadnews\env\minio-volume\data:/data
    ports:
      - "9000:9000"
      - "9090:9090"
    command: server /data --console-address ":9090"
    image: minio/minio:RELEASE.2022-09-01T23-53-36Z

  # headlines-seata:
  #   hostname: headlines-seata
  #   container_name: headlines-seata
  #   image: seataio/seata-server:1.5.2
  #   ports:
  #     - "7091:7091"
  #     - "8091:8091"
  #   environment:
  #     - STORE_MODE=db
  #     # 以SEATA_IP作为host注册seata server
  #     - SEATA_IP=192.168.80.1
  #     - SEATA_PORT=8091
  #   volumes:
  #     - D:\mycode\IdeaProjects\04microservices\heima-leadnews\env\seata-volume\config\resources:/seata-server/resources